# Kuramoto Fully-Connected

In [1]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
import pandas as pd
import math as math
import scipy.integrate as inte



### Determining order parameter by consistancy equation:

According to the analytical calculation for the Lorentzian frequency distribution: $1 = \lambda/(1+\sqrt{1+(\lambda R)^2}) \implies$
$R = \sqrt{\frac{\lambda-2}{\lambda}}$

In [2]:
def Rtheo(lamb):
    return np.sqrt((lamb-2)/lamb)

### Numerical calculation

First we create a routine for the Kuramoto model

In [3]:
def omLtz(N): # using the Lorentzian cumulative distribution for a regular frequency sampling
    omLtz = np.zeros(N)
    for i in range(N):
        omLtz[i] = np.tan(np.pi*(i+0.5-0.5*N)/N)
    return np.array([omLtz])

In [4]:
#def fKM(lamb,omarr,tharr):
#    N = np.size(tharr)
#    velarr = np.copy(omarr)
    
#    for i in range(N):
#        dvel = 0
#        for j in range(N):
#            dvel = dvel + math.sin(tharr[j]-tharr[i])

#        vel = velarr[i] + lamb*dvel/N
#        velarr[i] = vel
#    return velarr


In [5]:
#def fKM(lamb,omarr,tharr):
#    N = np.size(tharr)
#    adj = np.zeros([N,N])

    
#    for i in range(N):
#        for j in range(i+1,N):
            
#            adj[i,j] = math.sin(tharr[j]-tharr[i])
#            adj[j,i] = - adj[i,j]

#    velarr = omarr + lamb*np.sum(adj,1)/N
    #velarr[i] = vel
#    return velarr

In [6]:
#def fKM(lamb,omarr,tharr):
#    N = np.size(tharr)
#    adj = np.zeros([N,N])

    
#    adj = np.cos(th0).T*np.sin(th0) - np.sin(th0).T*np.cos(th0)

#    velarr = omarr + lamb*np.sum(adj,1)/N
    #velarr[i] = vel
#    return velarr

In [7]:
def Init(N):
    rng = np.random.default_rng(seed=42)
    th0 = np.zeros(N)
    for i in range(N):
        th0[i] = rng.uniform(-np.pi,np.pi)
    return np.array([th0])

def omLtz(N): # using the Lorentzian cumulative distribution for a regular frequency sampling
    omLtz = np.zeros(N)
    for i in range(N):
        omLtz[i] = np.tan(np.pi*(i+0.5-0.5*N)/N)
    return np.array([omLtz])
    
def order(tharr):
    N = np.size(tharr)
    Rx = np.sum(np.cos(tharr))/N
    Ry = np.sum(np.sin(tharr))/N
    R = np.sqrt(Rx**2+Ry**2)
    phi = np.asin(Ry/R)
    return (R,phi)


def fKM(lamb,omarr,tharr):
    N = np.size(tharr)
    R, phi = order(tharr)
    velarr = omarr + lamb*R*np.sin(phi-tharr)
    
    return velarr

In [8]:
def time_interval(dt,tf):
    Nt = int(tf/dt)+1
    time = np.linspace(0,tf,Nt)
    return (time,dt)
    
    
def integ(time,lamb,omarr,thini): #Heun method of integration
    N = np.size(thini)
    timelist, dt = time
    print(dt)
    Nt = np.size(timelist)
    integ = np.zeros([Nt,2,N])
    #print(integ[0,:,:])
    #print(np.array([thini,fKM(lamb,omarr,thini)]))
    
    integ[0,:,:] = np.array([thini[0],fKM(lamb,omarr,thini)[0]])
    th = thini
    
    
    for i in range(1,Nt):
        velaux = fKM(lamb,omarr,th)
        thaux = th + dt*velaux
        vel = (fKM(lamb,omarr,th)+fKM(lamb,omarr,thaux))/2.
        th = np.remainder(th + dt*vel,2.*np.pi)

        integ[i,:,:] = np.array([th[0],velaux[0]])
    return integ
    

In [163]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [119]:
a[:,0,0] = 1

In [149]:
a[0,:,:] = np.array([[1,1,1,1,1],[1,1,1,1,1]])

In [150]:
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [

In [27]:
N = 10000
omlist = omLtz(N)
th0 = Init(N)
lamb = 10.0
time = time_interval(0.01,50)

f1 = fKM(lamb,omlist,th0)

In [28]:
result = integ(time,lamb,omlist,th0)

0.01


In [43]:
result[1000,:,:][0]

array([5.5223948 , 4.86021607, 3.56915729, ..., 2.25308483, 0.22841345,
       2.17211332], shape=(10000,))

In [22]:
th0

array([[ 1.72131662, -0.38403809,  2.25313718, ..., -2.10268701,
        -0.79538593, -0.11996   ]], shape=(1, 10000))

In [42]:
order(result[1000,:,:][0])

(np.float64(0.8939456918929517), np.float64(-1.329484556785493))

In [30]:
Rtheo(lamb)

np.float64(0.8944271909999159)

In [47]:
np.histogram(result[100,:,:][0],15)

(array([ 565,  459,  368,  355,  366,  363,  402,  444,  621,  774, 1083,
        1284, 1187, 1002,  727]),
 array([1.96380014e-03, 4.20703733e-01, 8.39443666e-01, 1.25818360e+00,
        1.67692353e+00, 2.09566346e+00, 2.51440340e+00, 2.93314333e+00,
        3.35188326e+00, 3.77062319e+00, 4.18936313e+00, 4.60810306e+00,
        5.02684299e+00, 5.44558293e+00, 5.86432286e+00, 6.28306279e+00]))

In [35]:
omlist[0,6000]

np.float64(0.3250933680689823)

In [260]:
th = np.array([0,0])
#R = order(th)
#R

In [254]:
Rx = np.sum(np.cos(th))/2
Ry = np.sum(np.sin(th))/2
R = np.sqrt(Rx**2+Ry**2)
phi = np.asin(Ry/R)

In [255]:
R

np.float64(1.0)

In [261]:
order(th)

(np.float64(1.0), np.float64(0.0))

In [217]:
result[0,:,:][0]

array([ 1.72131662, -0.38403809,  2.25313718,  1.2400999 , -2.54985893,
        2.98842337,  1.64078914,  1.79739504, -2.33663096, -0.31173435])

In [210]:
np.remainder(np.array([7.0,8.0]),2*np.pi)

array([0.71681469, 1.71681469])

In [72]:
f1

array([[-6.30439023, -1.94113426, -1.00739853, -0.48710992, -0.18996161,
         0.13207912,  0.52130987,  1.00701602,  1.93271344,  6.3368761 ]])

In [202]:
np.cos(th0).T * np.sin(th0)

array([[-0.14825708,  0.05618235, -0.11637799, ...,  0.0784704 ,
         0.10127199, -0.03555731],
       [ 0.91667605, -0.34737641,  0.71956707, ..., -0.48518383,
        -0.62616642,  0.21985143],
       [-0.62348128,  0.23626961, -0.48941674, ...,  0.32999993,
         0.42588987, -0.14953293],
       ...,
       [-0.84251254,  0.31927198, -0.66135063, ...,  0.44593012,
         0.57550654, -0.20206439],
       [-0.72914944,  0.27631279, -0.57236352, ...,  0.38592861,
         0.49807006, -0.1748759 ],
       [-0.96049513,  0.36398175, -0.75396393, ...,  0.50837666,
         0.65609852, -0.23036081]], shape=(100, 100))

In [233]:
A = np.array([
    [1,2,3,2,2], [3,0,-2,2,2],[1,1,1,1,1]
])

In [234]:
np.sum(A,1)

array([10,  5,  5])

In [82]:
b = np.copy(a)

In [83]:
b

array([-6.31375151, -1.96261051, -1.        , -0.50952545, -0.15838444,
        0.15838444,  0.50952545,  1.        ,  1.96261051,  6.31375151])

In [84]:
a = 2*a

In [86]:
a

array([-12.62750303,  -3.92522101,  -2.        ,  -1.0190509 ,
        -0.31676888,   0.31676888,   1.0190509 ,   2.        ,
         3.92522101,  12.62750303])